### ISSUE TITLE
In fun(libname, pkgname) : couldn't connect to display ":0"

### ISSUE THREAD

**Issue by raubreywhite** [lozalojo/mem#1]
When I include the package `mem` in my `Imports` section of my R package's DESCRIPTION file and try to load my package I get the warning:

```
Warning message:
In fun(libname, pkgname) : couldn't connect to display ":0"
```

**Comment by lozalojo** [comment]
Are you using OSX? Seems like a OS specific problem and not related to mem, but I am not sure. Have you installed a window system like xquarz?

I am not expert in OSX, but I've tested mem under Captain.

**Comment by raubreywhite** [comment]
I'm using a headless Debian instance in a docker container from the rocker project (https://www.rocker-project.org).

There's no window system like xquarz (as it's all headless).

**Comment by raubreywhite** [comment]
Does `mem` try to automatically connect to an X11 instance?

**Comment by raubreywhite** [comment]
I found out the issue.

https://github.com/cran/sm/blob/2ef25145dd5cfa5481a2792b419cd6cac99c7765/NAMESPACE#L24

If any package has `import(tcltk)` in their NAMESPACE, then all subsequent packages give this warning on a headless computer.

**Comment by lozalojo** [comment]
Thanks for the feedback, I was clueless about it, I've installed mem in my debian server with no x windows and got no errors. I am not an expert in OSX.
